import type { GeneratedImage, VideoFormat } from "@video-generator/shared";

const TAG_COLORS = [
  "bg-green-500/20 text-green-400",
  "bg-blue-500/20 text-blue-400",
  "bg-purple-500/20 text-purple-400",
  "bg-yellow-500/20 text-yellow-400",
  "bg-pink-500/20 text-pink-400",
  "bg-cyan-500/20 text-cyan-400",
  "bg-red-500/20 text-red-400",
  "bg-orange-500/20 text-orange-400",
];

export function getTagColor(index: number): string {
  return TAG_COLORS[index % TAG_COLORS.length];
}

interface ImageCardProps {
  image: GeneratedImage;
  index: number;
  sceneLabel: string;
  onSelect: (id: number) => void;
  onRegenerate: (id: number) => void;
  isSelected: boolean;
  format?: VideoFormat;
}

export default function ImageCard({
  image,
  index,
  sceneLabel,
  onSelect,
  onRegenerate,
  isSelected,
  format = "16:9",
}: ImageCardProps) {
  const aspectClass = format === "9:16" ? "aspect-[9/16]" : "aspect-video";
  if (image.status === "processing" || image.status === "pending") {
    return (
      <div className={`relative rounded-lg overflow-hidden border border-gray-700 bg-gray-800 ${aspectClass} flex items-center justify-center`}>
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-4 border-gray-600 border-t-green-400 rounded-full animate-spin" />
          <span className="text-gray-400 text-sm">Generating...</span>
        </div>
        <div className="absolute bottom-0 left-0 right-0 flex justify-between items-center px-3 py-2 bg-gradient-to-t from-black/80 to-transparent">
          <span className="text-xs text-gray-300">
            ({index + 1}) {image.model}
          </span>
          <span className="text-xs text-gray-500">{sceneLabel}</span>
        </div>
      </div>
    );
  }

  if (image.status === "failed") {
    return (
      <div className={`relative rounded-lg overflow-hidden border border-red-700/50 bg-gray-800 ${aspectClass} flex items-center justify-center`}>
        <div className="flex flex-col items-center gap-2 text-red-400">
          <svg
            className="w-8 h-8"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z"
            />
          </svg>
          <span className="text-sm">Generation failed</span>
          <button
            onClick={() => onRegenerate(image.id)}
            className="mt-1 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-gray-200 text-xs rounded-md transition-colors cursor-pointer"
          >
            Retry
          </button>
        </div>
        <div className="absolute bottom-0 left-0 right-0 flex justify-between items-center px-3 py-2 bg-gradient-to-t from-black/80 to-transparent">
          <span className="text-xs text-gray-300">
            ({index + 1}) {image.model}
          </span>
          <span className="text-xs text-gray-500">{sceneLabel}</span>
        </div>
      </div>
    );
  }

  return (
    <div
      className={`relative rounded-lg overflow-hidden border-2 cursor-pointer transition-all group ${
        isSelected
          ? "border-green-500 shadow-lg shadow-green-500/20"
          : "border-gray-700 hover:border-gray-500"
      }`}
      onClick={() => onSelect(image.id)}
    >
      <div className={`${aspectClass} bg-gray-800`}>
        {image.imageUrl ? (
          <img
            src={image.imageUrl}
            alt={`Generated by ${image.model}`}
            className="w-full h-full object-cover"
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-gray-500">
            No image
          </div>
        )}
      </div>

      {/* Action icons on hover */}
      <div className="absolute top-2 right-2 flex gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity">
        {isSelected && (
          <div className="w-8 h-8 rounded-full bg-green-500 flex items-center justify-center opacity-100">
            <svg
              className="w-5 h-5 text-white"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M5 13l4 4L19 7"
              />
            </svg>
          </div>
        )}
      </div>

      {/* Always show checkmark if selected */}
      {isSelected && (
        <div className="absolute top-2 right-2 w-8 h-8 rounded-full bg-green-500 flex items-center justify-center">
          <svg
            className="w-5 h-5 text-white"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M5 13l4 4L19 7"
            />
          </svg>
        </div>
      )}

      {/* Bottom overlay with model name and scene label */}
      <div className="absolute bottom-0 left-0 right-0 flex justify-between items-center px-3 py-2 bg-gradient-to-t from-black/80 to-transparent">
        <span className="text-xs text-gray-200 font-medium">
          ({index + 1}) {image.model}
        </span>
        <span className="text-xs text-gray-400">{sceneLabel}</span>
      </div>
    </div>
  );
}
